/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package basiclibrary;


import java.sql.SQLOutput;
import java.text.DecimalFormat;
import java.util.*;

public class Library {
    boolean debug = false;
    public int[] roll(int n) {
        int[] intArray;
        intArray = new int[n];
        Random dice = new Random();
        for(int i = 0; i < n; i++) {
            int randNum = dice.nextInt(6) + 1;
            intArray[i] = randNum;
        }
        if(debug) {
            System.out.println(Arrays.toString(intArray));
        }
        return intArray;
    }

    public boolean containsDuplicates(int[] intArrayArg) {
        if(debug) {
            System.out.println(Arrays.toString(intArrayArg));
        }
        boolean duplicate = false;
        for(int i = 0; i < intArrayArg.length; i ++) {
            for(int j = 0; j < intArrayArg.length; j++) {
                if(i != j && intArrayArg[i] == intArrayArg[j]) {
                    duplicate = true;
                    if(debug) {
                        System.out.println("Duplicates at i: "+i+ ", j: "+j);
                    }
                    break;
                }
            }
        }
        return duplicate;
    }

    public double arrayAverage(int[] intArrayArg) {
        //https://stackoverflow.com/a/8895395/16970042
        DecimalFormat numberFormat = new DecimalFormat("#.00");
        int total = 0;
        for(int num : intArrayArg) {
            total += num;
        }
        double average = (double) total / intArrayArg.length;
        if(debug) {
            System.out.println("Average: " + numberFormat.format(average));
        }
        return average;
    }

    public int[] lowestAverageArray(int[][] arrOfArrArg) {
        double currentLowestAvg = Double.POSITIVE_INFINITY;
        int currentLowestIndex = 0;
        for(int i = 0; i < arrOfArrArg.length; i++) {
            int currentArrSum = 0;
            for(int num : arrOfArrArg[i]) {
                currentArrSum += num;
            }
            double currentArrAvg = (double) currentArrSum / arrOfArrArg[i].length;
            if(debug) {
                System.out.println("At index " + i + ", currentArrSum = " + currentArrSum + ", currentArrAvg = " + currentArrAvg);
            }
            if(currentArrAvg < currentLowestAvg) {
                currentLowestAvg = currentArrAvg;
                currentLowestIndex = i;
            }
        }
        if(debug) {
            System.out.println(Arrays.toString(arrOfArrArg[currentLowestIndex]));
        }
        return arrOfArrArg[currentLowestIndex];
    }

    public String analyzeWeatherData(int[][] arrayOfArraysArg) {
        int lowestTemp = Integer.MAX_VALUE;
        int highestTemp = Integer.MIN_VALUE;
        String finalString = "";
        ArrayList<String> missingTemps =  new ArrayList<>();
        ArrayList<Integer> temperatures = new ArrayList<>();
        HashSet<Integer> monthTemperatures = new HashSet<>();
        for(int[] weeklyTemps : arrayOfArraysArg) {
            for(int dayTemp : weeklyTemps) {
                temperatures.add(dayTemp);
                if(dayTemp < lowestTemp) {
                    lowestTemp = dayTemp;
                } else if (dayTemp > highestTemp) {
                    highestTemp = dayTemp;
                }
            }
        }
        for(int i = lowestTemp; i < highestTemp; i++) {
            if(!temperatures.contains(i)) {
                missingTemps.add("Never saw temperature: " + i);
                finalString += "Never saw temperature: " + i + "\n";
            }
        }
        if(debug) {
            System.out.println("Missing Temps: " + missingTemps);
            System.out.println("Lowest Temp: " + lowestTemp);
            System.out.println("Highest Temp: " + highestTemp);
            System.out.println(monthTemperatures);
        }

        monthTemperatures.addAll(temperatures);
        finalString += "High: " +highestTemp+ "\nLow: " +lowestTemp + "\n";
        if(debug) {
        System.out.println(finalString);
        }
        return finalString;
    }

    public String tally(List<String> arrayOfStringsArg) {
        String largestKey = "";
        int largestValue = Integer.MIN_VALUE;
        HashMap<String, Integer> numVotes = new HashMap<>();
        for(String string : arrayOfStringsArg) {
            if(numVotes.containsKey(string) == false) {
                numVotes.put(string, 1);
                if(largestKey.equals("")) {
                    largestKey = string;
                    largestValue = 1;
                } else {
                    if(largestValue < numVotes.get(string)) {
                        largestKey = string;
                        largestValue = numVotes.get(string);
                    }
                }
            } else {
                numVotes.put(string, numVotes.get(string) + 1);
                if(largestValue < numVotes.get(string)) {
                    largestKey = string;
                    largestValue = numVotes.get(string);
                }
            }
        }
        String finalString = largestKey + " received the most votes with " +largestValue+ " votes!";
        if(debug) {
        System.out.println(largestKey);
        System.out.println(numVotes);
        System.out.println(finalString);
        }
        return finalString;
    }

}
